### ISSUE TITLE
Trying to use this Posh-Kentico

### ISSUE THREAD

**Issue by awcoats** [clcrutch/posh-kentico#35]
I'm trying to use this module - with the following:

`Connect-CMSApplication -WebRoot ".\src\CMS" -ConnectionString "Data Source=.\MSSQLSERVER01;Initial Catalog=blah;Integrated Security=False;Persist Security Info=False;User ID=usr;Password=blah;Connect Timeout=60;Encrypt=False;Current Language=English;"` 

`Initialize-CMSApplication -WebRoot ".\src\CMS" -ConnectionString "Data Source=.\MSSQLSERVER01;Initial Catalog=blah;Integrated Security=False;Persist Security Info=False;User ID=usr;Password=blah;Connect Timeout=60;Encrypt=False;Current Language=English;" `

`Get-CMSSite`

```
Get-CMSSite : Application pre-initialization has to be executed before accessing this property.
At line:1 char:1
+ Get-CMSSite
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CMSSite], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PoshKentico.Cmdlets.Configuration.Sites.GetCmsSiteCmdlet
```

I am trying to connect to the Kentico CMS version 12.0.48

Do you have some examples of how to use the Module? 
Any ideas of what I'm doing wrong?

Regards,

Andrew

**Comment by clcrutch** [comment]
For the initial run, it is necessary to run PowerShell as admin so that it can query IIS.  Can you confirm that you were running as an administrator on the server with Kentico installed?

**Comment by awcoats** [comment]
Running as Administrator resolved my issue. Thank you.
